#include <stdlib.h>
#include <stdio.h>
#include <string.h>

/*
 * Convert an obsolete trace file generated by destor 0.1 
 *  into a trace file that can be read by a new version of destor.
 */
int main(int argc, char** argv){
    if(argc<2)
        return 1;

    char* path = argv[1];
    char new_path[256];

    puts(path);
    strcpy(new_path, path);
    strcat(new_path, ".new");
    puts(new_path);

    FILE* fp = fopen(path, "r");
    FILE* trace = fopen(new_path, "w");

    if(fp == 0) return 1;

    char buf[128];
    char hash[40];
    int length;
    fgets(buf, 128, fp);
    int i = 0;
    while(strcmp(buf, "STREAM_END") != 0){
        if(strncmp(buf, "fileindex=", strlen("fileindex=")) == 0){
            char* temp = "_file%d";
            char filename[256];
            sprintf(filename, temp, i);
            fprintf(trace, "file start %zd\n",strlen(filename));
            fprintf(trace, "%s\n",filename);
        }else if(strcmp(buf, "FILE_END\n") == 0){
            fputs("file end\n", trace);
            i++;
        }else{
            memcpy(hash, buf, 40);
            length = atoi(buf+41);
            fprintf(trace, "%s %d\n", hash, length);
        }
        fgets(buf, 128, fp);
    }

    fputs("stream end", trace);
    fclose(fp);
    fclose(trace);

    return 0;
}
